import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { capitalIllustration, extractNumberedSection, plainExcerpt, publicBookModel } from '../lib/book-marketing.mjs';

const record = { id: 'test', fields: { Chapitre: '2 — Holdings, flux intragroupe et capitalisation', 'Contenu V1': 'Ouverture\n\n## 21. La holding\n\n### La scène\n\nPremier paragraphe réel.\n\nDeuxième paragraphe.\n\n## 22. Autre cas\n\nNe pas publier ce texte par accident.' } };
test('public excerpt stays inside its numbered section', () => { const sample = extractNumberedSection(record.fields['Contenu V1'], 21); assert.equal(sample.title, 'La holding'); assert.match(sample.markdown, /Premier paragraphe/); assert.doesNotMatch(sample.markdown, /Ne pas publier/); assert.equal(extractNumberedSection('nothing', 21), null); });
test('public catalog has no private record metadata or whole manuscript', () => { const value = publicBookModel([record, { fields: { Chapitre: 'Note privée', 'Contenu V1': 'INTERNAL_SECRET' } }]); assert.equal(value.sectionCount, 1); assert.equal(value.samples.length, 1); assert.doesNotMatch(JSON.stringify(value), /INTERNAL_SECRET|cellValuesByFieldId|sourceLocale/); assert.equal(value.sections[0].category, 'entreprise'); });
test('empty source does not invent a book inventory', () => { assert.deepEqual(publicBookModel([]), { sectionCount: 0, sections: [], samples: [] }); });
test('comparison is accurate and distinguishes company cash from personal proceeds', () => { const value = capitalIllustration(); assert.equal(value.personal, 68600); assert.equal(value.holdingTax, 1250); assert.equal(value.holding, 98750); assert.equal(value.retainedDifference, 30150); assert.equal(value.afterPersonalDistribution, 67742.5); assert.throws(() => capitalIllustration(NaN)); assert.throws(() => capitalIllustration(-1)); });
test('plain previews keep full paragraphs', () => { assert.equal(plainExcerpt('### La scène\n\nUne vraie histoire.'), 'Une vraie histoire.'); });
test('purchase gate is preserved and does not publish configuration', () => { const source = readFileSync(new URL('../lib/book-offer.js', import.meta.url), 'utf8'); assert.match(source, /commercialReadiness/); assert.match(source, /readiness\.ready \? '\/achat-guide' : ''/); assert.doesNotMatch(source, /return\s+config/); });
test('book signup records a narrowly scoped explicit request', () => { const source = readFileSync(new URL('../app/api/leads/route.js', import.meta.url), 'utf8'); assert.match(source, /allowedOrigin\(request\)/); assert.match(source, /body\.consent !== true/); assert.match(source, /BOOK_LAUNCH_WAITLIST/); assert.match(source, /MAX_BODY_BYTES/); });
test('canonical mascot route cannot proxy an arbitrary URL', () => { const source = readFileSync(new URL('../app/api/brand-image/[pose]/route.js', import.meta.url), 'utf8'); assert.match(source, /Object\.hasOwn\(POSES, pose\)/); assert.match(source, /airtableusercontent\.com/); assert.match(source, /redirect: 'error'/); });
