import Brand from './Brand';
import { BookAction, BookSignals, OfficialHibou } from './BookExperience';
import HoldingLombard from './HoldingLombard';
import './book-store.css';
import './book-store-voice.css';

export function StoreHeader({ guide = false }) {
  return <header className="store-header"><a href="#main-content" className="store-skip">Aller au contenu</a><nav className="store-nav" aria-label="Navigation principale"><Brand href="/" logoUrl="/hibou-monocle.webp" /><div className="store-navlinks"><a href="/#methode">D4 · D5 · D6</a><a href="/guide#exemple">Exemple holding</a><a href="/#services">Sur mesure</a></div><BookAction href={guide ? '#offre' : '/guide'} placement="header" className="store-header-cta">Le livre · 29 €</BookAction></nav><div className="store-mobile-nav"><a href="/#methode">D4 · D5 · D6</a><a href="/#services">Montages sur mesure ↗</a></div></header>;
}
export function StoreFooter() {
  return <footer className="store-footer"><div className="store-wrap"><Brand href="/" logoUrl="/hibou-monocle.webp" /><p>Comprendre les règles. Exploiter les failles.</p><div className="store-footer-links"><a href="/guide">Le livre</a><a href="/services">Montages sur mesure</a><a href="/mentions-legales">Mentions légales</a><a href="/cgv">CGV</a><a href="/confidentialite">Confidentialité</a><a href="/conditions-utilisation">Conditions d’utilisation</a><a href="/retractation">Rétractation</a></div><p className="store-small">Contenus pédagogiques et informatifs. Les exemples ne constituent pas un conseil juridique, fiscal ou financier individualisé.</p></div></footer>;
}
function ProductVisual() {
  return <figure className="store-product-visual"><div className="store-book-object"><span className="store-book-edition">D4 · D5 · D6</span><h2>Le guide du<br/><em>Hibou Rusé</em></h2><OfficialHibou pose="revele" priority className="store-cover-owl" /><div className="store-book-baseline">OPTIMISÉS. AGRESSIFS.<br/>BORDERLINE.</div></div><div className="store-product-note"><span className="store-note-symbol" aria-hidden="true">↗</span><p>Le livre du Hibou.<br/><strong>29 € · paiement unique.</strong></p></div><figcaption>Guide numérique · consultation en ligne.</figcaption></figure>;
}
export function MethodLevels() {
  return <section className="store-wrap store-method" id="methode" aria-labelledby="method-title"><div className="store-method-heading"><p className="store-overline">LE TERRAIN DE JEU DU HIBOU</p><h2 id="method-title">Optimisés. Agressifs. <em>Borderline.</em></h2><p>Les règles ont des angles morts. C’est là que le Hibou regarde.</p></div><div className="store-levels"><article data-level="D4"><span className="store-level-badge">D4</span><div><h3>Légal, mais optimisé.</h3><p>Les leviers autorisés. Les bonnes combinaisons. Pas le minimum syndical.</p></div></article><article data-level="D5"><span className="store-level-badge">D5</span><div><h3>Agressif.</h3><p>Des montages qui poussent plus loin les textes, les exceptions et leurs interactions.</p></div></article><article data-level="D6"><span className="store-level-badge">D6</span><div><h3>Borderline.</h3><p>Les zones grises, décortiquées. Là où les faits et l’interprétation font basculer le résultat.</p></div></article></div></section>;
}
export function ServiceOffers({ standalone = false }) {
  return <section className={standalone ? 'store-service-section' : 'store-wrap store-service-section'} id="services" aria-labelledby="services-title"><div className="store-section-heading"><p className="store-overline">LE LIVRE. ET VOTRE CAS.</p><h2 id="services-title">Votre situation n’est pas standard.<br/>Pourquoi votre étude le serait ?</h2></div><div className="store-service-cards"><article className="store-service-offer"><p className="store-overline">UNE SÉLECTION CIBLÉE</p><h3>Montages spécifiques</h3><strong>500 €</strong><p>Vous exposez vos objectifs. Le Hibou sélectionne les montages à explorer pour vos thèmes : rémunération, entreprise, crédit, patrimoine.</p><p className="store-service-deliverable">Une sélection argumentée, les scénarios comparés et les points qui changent le résultat.</p><BookAction href="/services?offre=selection#demande" secondary placement="service-selection">Demander ma sélection</BookAction></article><article className="store-service-offer is-bespoke"><p className="store-overline">UN SUJET HORS DES CASES</p><h3>Montage sur mesure</h3><strong>Sur devis</strong><p>Une idée atypique ? Une combinaison à creuser ? Le Hibou étudie votre question et construit un dossier spécifique, plutôt qu’une réponse copiée-collée.</p><p className="store-service-deliverable">Périmètre, livrable et prix définis avant la commande.</p><BookAction href="/services?offre=sur-mesure#demande" secondary placement="service-bespoke">Demander un devis</BookAction></article></div></section>;
}
const BOOK_TEASERS = [
  ['RÉMUNÉRATION', 'Jusqu’où peut-on légalement réduire l’impôt ?', 'Les cas où la qualification du revenu change fortement le résultat.'],
  ['SOCIÉTÉ', 'Faire sortir de la valeur autrement qu’en salaire', 'Salaire, dividendes, frais, actifs, droits, crédit : comparer les circuits.'],
  ['STRUCTURES', 'Association, fondation, coopérative : quand la structure change la donne', 'Flux, droits, gouvernance et financement ne fonctionnent plus de la même façon.'],
  ['IMMOBILIER', 'Qui détient quoi ? Et qui paie quoi ?', 'SCI, SCPI, usufruit, nue-propriété et démembrement.'],
  ['STATUTS', 'Revenus atypiques. Statuts particuliers. Règles différentes.', 'Quand votre situation sort du cas standard, la bonne qualification devient centrale.'],
  ['RÉALITÉ', 'Ce qui tient sur le papier… et dans les faits', 'Les montages séduisants ne valent que si la réalité suit.'],
];

function BookTopics() {
  return <div className="store-topics" id="contenu"><p className="store-overline">QUELQUES MONTAGES COMPRIS DANS LE LIVRE</p><div className="store-topic-grid">{BOOK_TEASERS.map(([kicker,title,text], index) => <article className="store-topic-card" key={title}><div className="store-topic-meta"><span>{kicker}</span><span>{String(index + 1).padStart(2, '0')}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div><p className="store-small store-topic-note">Une sélection seulement. Le site ne publie ni le sommaire complet ni le texte du livre.</p></div>;
}

function OfferBlock({ offer }) {
  return <section className="store-offer-section" id="offre"><div className="store-wrap store-offer-grid"><div><p className="store-overline">LE LIVRE DU HIBOU</p><h2>Les classiques ?<br/><em>Vous les connaissez déjà.</em></h2><p className="store-lead">Des montages atypiques, travaillés et expliqués avec des cas concrets. De l’optimisation assumée, pas un catalogue de placements.</p><div className="store-included"><p><span>01</span> Comprendre le montage et ce qu’il peut changer.</p><p><span>02</span> Voir les chiffres et les combinaisons.</p><p><span>03</span> Repérer le détail qui fait tenir — ou tomber — l’ensemble.</p></div><BookTopics/><details className="store-reading-order"><summary>Dois-je lire le livre dans l’ordre ?</summary><p>Non. Commencez par le sujet qui vous intéresse.</p></details></div><div className="store-offer-card"><span className="store-pill">GUIDE NUMÉRIQUE</span><h3>Le guide du Hibou Rusé</h3><p className="store-offer-price">{offer.priceLabel}</p><p className="store-price-line">Paiement unique.</p><BookAction href={offer.purchaseUrl || '/achat-guide'} purchase placement="offer">Acheter le livre</BookAction><p className="store-offer-status">Accès au lecteur personnel du Hibou après confirmation du paiement.</p><div className="store-edition-note" id="edition"><p>{offer.earlyAccess ? 'Édition en accès anticipé : les enrichissements du même guide seront ajoutés sans nouvel achat.' : 'Vous achetez l’édition disponible à la date de votre commande.'}</p></div></div></div></section>;
}

export default function BookStore({ offer, guide = false }) {
  const purchaseHref = offer.purchaseUrl || '/achat-guide';
  return <div className="store store-assertive" data-store-version="2026-10-03-no-excerpts"><StoreHeader guide={guide}/><main id="main-content"><section className="store-hero"><div className="store-wrap store-hero-grid"><div className="store-hero-copy"><p className="store-overline">FISCALITÉ · ENTREPRISE · PATRIMOINE</p><h1>{guide ? <>Le guide qui va chercher<br/><em>les failles.</em></> : <>Comprendre les règles.<br/><em>Exploiter les failles.</em></>}</h1><p className="store-hero-intro">{offer.hero['Sous-titre'] || 'Des montages atypiques. De l’optimisation assumée. Du légal bien ficelé à l’agressif, jusqu’aux zones borderline.'}</p><p className="store-hero-promise">PEA, assurance-vie, 150-0 B ter : le Hibou ne s’arrête pas aux classiques.</p><div className="store-actions"><BookAction href={purchaseHref} placement="hero" purchase>Acheter le livre · {offer.priceLabel}</BookAction><BookAction href="#exemple" secondary placement="hero-example">Voir l’exemple holding</BookAction></div><p className="store-hero-meta">Paiement unique · Lecture en ligne · <a href="#services">Montages spécifiques et sur mesure ↗</a></p></div><ProductVisual/></div></section>
    <MethodLevels/>
    <section className="store-example-section" id="exemple"><div className="store-wrap"><div className="store-section-heading"><p className="store-overline">HOLDING + FINANCEMENT PERSONNEL</p><h2>Votre argent peut travailler.<br/><em>Sans tout distribuer.</em></h2><p>D’abord capitaliser dans la holding. Ensuite, étudier le nantissement de vos titres personnels pour emprunter.</p></div><HoldingLombard/></div></section>
  <OfferBlock offer={offer}/>
    <ServiceOffers/>
  </main><StoreFooter/><div className="store-mobile-bar"><span>Le livre du Hibou<strong>{offer.priceLabel} · paiement unique</strong></span><BookAction href={purchaseHref} placement="mobile" purchase>Acheter le livre</BookAction></div><BookSignals/></div>;
}
