import Brand from './Brand';
import { markdownToBookHtml } from '../lib/book-renderer.mjs';
import { BookAction, BookContents, BookPreview, BookSignals, CapitalComparison, NotifyBook, OfficialHibou } from './BookExperience';
import './book-store.css';

export function StoreHeader({ guide = false }) {
  return <header className="store-header"><a href="#main-content" className="store-skip">Aller au contenu</a><nav className="store-nav" aria-label="Navigation principale"><Brand href="/" logoUrl="/hibou-monocle.webp" /><div className="store-navlinks"><a href="/guide#extrait">Lire un extrait</a><a href="/guide#contenu">Au sommaire</a></div><BookAction href={guide ? '#offre' : '/guide'} placement="header" className="store-header-cta">{guide ? 'Le livre' : 'Découvrir le livre'}</BookAction></nav></header>;
}
export function StoreFooter() {
  return <footer className="store-footer"><div className="store-wrap"><Brand href="/" logoUrl="/hibou-monocle.webp" /><p>Comprendre les règles. Exploiter les failles.</p><div className="store-footer-links"><a href="/guide">Le livre</a><a href="/services">Approfondir un sujet</a><a href="/mentions-legales">Mentions légales</a><a href="/cgv">CGV</a><a href="/confidentialite">Confidentialité</a><a href="/conditions-utilisation">Conditions d’utilisation</a><a href="/retractation">Rétractation</a></div><p className="store-small">Contenus pédagogiques et informatifs. Les exemples ne constituent pas un conseil juridique, fiscal ou financier individualisé.</p></div></footer>;
}

function ProductVisual() {
  return <figure className="store-product-visual"><div className="store-book-object"><span className="store-book-edition">LA BIBLIOTHÈQUE DU HIBOU</span><h2>Le guide du<br/><em>Hibou Rusé</em></h2><OfficialHibou pose="revele" priority className="store-cover-owl" /><div className="store-book-baseline">L’ARGENT. LES RÈGLES.<br/>LES CHEMINS DE TRAVERSE.</div></div><div className="store-product-note"><span className="store-note-symbol" aria-hidden="true">↗</span><p>Une autre façon<br/><strong>de regarder votre argent.</strong></p></div><figcaption>Guide numérique, à lire en ligne. Représentation du produit.</figcaption></figure>;
}

function OfferBlock({ offer }) {
  return <section className="store-offer-section" id="offre"><div className="store-wrap store-offer-grid"><div><p className="store-overline">LE GUIDE DU HIBOU RUSÉ</p><h2>Le prochain déclic<br/>se trouve peut-être ici.</h2><p className="store-lead">Ne vous contentez pas de connaître les produits. Comprenez les mécanismes, les arbitrages et les combinaisons qu’ils rendent possibles.</p><div className="store-included"><p><span>01</span> Des situations concrètes, pas seulement des définitions.</p><p><span>02</span> Les mécanismes, leurs conditions et leurs points de rupture.</p><p><span>03</span> Une lecture par sujet pour aller droit à ce qui vous intéresse.</p></div></div><div className="store-offer-card"><span className="store-pill">GUIDE NUMÉRIQUE</span><h3>Le livre du Hibou</h3><p className="store-offer-price">{offer.priceLabel}</p><p className="store-small">Paiement unique, sans abonnement.<br/>Total et taxes éventuelles précisés avant paiement.</p>{offer.ready ? <BookAction href={offer.purchaseUrl} purchase placement="offer">Accéder au livre</BookAction> : <BookAction href="#ouverture" placement="offer-waitlist">Être averti de l’ouverture</BookAction>}<p className="store-offer-status">{offer.ready ? 'Paiement sécurisé par Lemon Squeezy.' : 'La vente n’est pas encore ouverte. Aucun paiement n’est demandé.'}</p><a className="store-inline-link" href="#extrait">D’abord, lire un vrai montage ↗</a></div></div></section>;
}

export default function BookStore({ offer, guide = false }) {
  const sample = offer.samples.find((item) => item.number === 21);
  const previewSamples = offer.samples.map(({ markdown, ...item }) => item);
  const heroTarget = guide ? (offer.ready ? offer.purchaseUrl : '#ouverture') : '/guide';
  const heroLabel = guide ? (offer.ready ? `Accéder au livre · ${offer.priceLabel}` : 'Être averti de l’ouverture') : `Découvrir le livre · ${offer.priceLabel}`;
  return <div className="store"><StoreHeader guide={guide}/><main id="main-content"><section className="store-hero"><div className="store-wrap store-hero-grid"><div className="store-hero-copy"><p className="store-overline">FISCALITÉ · ENTREPRISE · PATRIMOINE</p><h1>{guide ? <>Les montages que vous n’auriez pas pensé à <em>chercher.</em></> : <>Comprendre les règles.<br/><em>Exploiter les failles.</em></>}</h1><p className="store-hero-intro">{guide ? 'Vous connaissez peut-être les produits. Découvrez les autres chemins que votre argent peut emprunter.' : (offer.hero['Sous-titre'] || 'Entreprise, rémunération, patrimoine : découvrez d’autres façons de faire circuler, conserver et transmettre la valeur.')}</p><p className="store-hero-promise">Des cas concrets. Des chiffres. Et les détails qui changent tout.</p><div className="store-actions"><BookAction href={heroTarget} placement="hero" purchase={guide && offer.ready}>{heroLabel}</BookAction><BookAction href="#extrait" secondary placement="hero-excerpt">Lire un vrai montage</BookAction></div><p className="store-hero-meta">Livre numérique · Paiement unique · Extrait gratuit sans inscription</p>{guide && <p className="store-edition-status">{offer.earlyAccess ? 'Édition en accès anticipé, encore incomplète.' : 'Consultez le contenu disponible et les informations de l’édition ci-dessous.'}</p>}</div><ProductVisual/></div></section>

    <section className="store-discover store-wrap" id="decouvertes"><div className="store-section-heading"><p className="store-overline">CHANGER DE PERSPECTIVE</p><h2>Vous pensiez avoir<br/>fait le tour de la question ?</h2><p>Le Hibou ne s’arrête pas au premier réflexe. Il regarde qui possède, qui perçoit, qui finance. Puis il compare les chemins possibles.</p></div><div className="store-discovery-grid">{(offer.samples.length ? offer.samples : [
      { number: 1, kicker: 'ENTREPRISE', promise: 'Posséder un actif ou l’exploiter : pourquoi tout mettre dans la même boîte ?' },
      { number: 2, kicker: 'RÉMUNÉRATION', promise: 'Être payé pour son travail. Ou participer aussi à la valeur créée ?' },
      { number: 3, kicker: 'PATRIMOINE', promise: 'Et si la question était moins combien transmettre que quoi et quand ?' },
    ]).map((item, index) => <article className="store-discovery-card" key={item.number}><div className="store-discovery-top"><span>{item.kicker}</span><span aria-hidden="true">0{index + 1}</span></div><h3>{item.promise}</h3><p>{index === 0 ? 'Changer le circuit de l’argent, avant de comparer les taux.' : index === 1 ? 'Distinguer la propriété, le prix et le droit d’utilisation.' : 'Séparer ce qui se transmet de ce que l’on souhaite conserver.'}</p><BookAction href={index === 0 ? '#extrait' : '#feuilleter'} secondary placement={`discovery-${index}`}>{index === 0 ? 'Voir le cas chiffré' : 'Ouvrir un extrait'}</BookAction></article>)}</div></section>

    <section className="store-example-section" id="extrait"><div className="store-wrap"><div className="store-section-heading"><p className="store-overline">UN VRAI CAS, AVANT D’ACHETER</p><h2>100 000 €.<br/><em>Deux circuits. Deux logiques.</em></h2><p>Faut-il percevoir les dividendes personnellement ou les laisser travailler dans une holding ? Touchez les deux options pour voir ce qui change.</p></div><CapitalComparison/>{sample && <details className="store-full-excerpt"><summary><span>Lire le montage complet du livre</span><span aria-hidden="true">+</span></summary><article className="store-excerpt-text"><p className="store-overline">EXTRAIT INTÉGRAL · ÉDITION ACTUELLE</p><h3>{sample.title}</h3><div dangerouslySetInnerHTML={{ __html: markdownToBookHtml(sample.markdown) }}/></article></details>}<div className="store-example-next"><p>Ce qui compte, ce n’est pas seulement le taux.<br/><strong>C’est le chemin que suit la valeur.</strong></p><BookAction href={guide ? '#offre' : '/guide'} placement="after-example">Découvrir le livre</BookAction></div></div></section>

    <section className="store-wrap store-preview-section" id="feuilleter"><div><p className="store-overline">OUVREZ LE LIVRE</p><h2>Du concret.<br/>Pas du remplissage.</h2><p className="store-lead">Un mécanisme, une histoire, un changement de perspective. Parcourez de vrais passages avant de décider.</p><p>La propriété intellectuelle, les flux entre sociétés, l’immobilier, les modes de rémunération : le guide relie les sujets que l’on vous présente trop souvent séparément.</p><div className="store-quote"><span aria-hidden="true">“</span><p>Vous connaissez peut-être les produits.<br/><strong>Ce livre s’intéresse à la façon dont leurs règles se combinent.</strong></p></div><BookAction href="#contenu" secondary placement="preview-to-contents">Explorer le sommaire</BookAction></div><BookPreview samples={previewSamples}/></section>

    <section className="store-contents-section" id="contenu"><div className="store-wrap"><div className="store-section-heading"><p className="store-overline">COMMENCEZ PAR CE QUI VOUS CONCERNE</p><h2>Votre entreprise.<br/>Votre rémunération. Votre patrimoine.</h2><p>Explorez les sections réellement présentes dans le lecteur. Les titres ci-dessous sont lus directement dans l’édition disponible, pas dans une liste de projets.</p></div><BookContents sections={guide ? offer.sections : offer.sections.slice(0, 7)}/>{!guide && <div className="store-center"><BookAction href="/guide#contenu" secondary placement="full-contents">Voir tout le sommaire</BookAction></div>}<div className="store-edition-box" id="edition"><strong>{offer.sectionCount ? `${offer.sectionCount} sections rédigées dans le lecteur actuel` : 'Composition de l’édition en cours de vérification'}</strong><p>{offer.edition ? `Édition ${offer.edition}. ` : ''}{offer.earlyAccess ? 'Cette version est en accès anticipé et incomplète. Les textes restent des brouillons éditoriaux ; certains passages portent la mention « À VÉRIFIER ». ' : ''}Les sections sans texte ne sont pas comprises. Les sections du lecteur ne correspondent pas au nombre de fiches de la bibliothèque de travail.</p><p>Lorsqu’une version enrichie du même guide sera publiée, elle remplacera l’édition actuelle dans votre accès, sans nouvel achat. Aucune date ni quantité de nouveaux chapitres n’est annoncée.</p></div></div></section>

    <OfferBlock offer={offer}/>
    {!offer.ready && <section className="store-wrap store-launch" id="ouverture"><div><p className="store-overline">NE PERDEZ PAS LE FIL</p><h2>Le livre vous intrigue ?<br/>Soyez prévenu de son ouverture.</h2><p>Vous avez lu l’extrait. Laissez votre e-mail pour retrouver le Hibou lorsque la vente ouvrira.</p></div><NotifyBook/></section>}

    <section className="store-wrap store-faq-section" id="questions"><div className="store-section-heading"><p className="store-overline">AVANT D’OUVRIR LE LIVRE</p><h2>Les réponses, sans détour.</h2></div><div className="store-faq"><details><summary>À qui s’adresse le guide ?</summary><p>Aux entrepreneurs, indépendants, dirigeants et lecteurs curieux de comprendre comment s’articulent entreprise, rémunération et patrimoine. Certains montages sont spécialisés : le sommaire et les extraits vous permettent de juger de leur intérêt avant l’achat.</p></details><details><summary>Est-ce encore un guide sur le PEA et l’assurance-vie ?</summary><p>Ce n’est pas un catalogue de produits. Le point de départ est une situation : un actif, une rémunération, une société, une transmission. Le livre examine les règles qui interagissent et les différences entre plusieurs architectures.</p></details><details><summary>Que vais-je recevoir après le paiement ?</summary><p>{offer.deliveryProvider === 'hibou_reader' ? 'Après confirmation du paiement, vous accédez personnellement au lecteur sécurisé du Hibou depuis la page de confirmation et le lien du reçu. La lecture se fait en ligne, sur ordinateur ou téléphone. Il ne s’agit pas d’un livre papier ni d’un PDF téléchargeable.' : 'Un accès personnel au guide numérique disponible à la date d’achat. Les modalités exactes de livraison sont précisées dans le parcours de commande.'} L’édition disponible est décrite au-dessus.</p></details><details><summary>Le prix est-il mensuel ?</summary><p>Non. Le prix annoncé est de {offer.priceLabel} en paiement unique, sans abonnement. Le total exact et les taxes éventuelles sont indiqués avant validation du paiement chez Lemon Squeezy.</p></details><details><summary>Dois-je lire le livre dans l’ordre ?</summary><p>Vous pouvez commencer par les thèmes qui vous concernent. Le sommaire présente les sections disponibles ; les passages sur les mécanismes, les conditions et les limites se lisent ensemble.</p></details><details id="methode"><summary>D4, D5, D6 : qu’est-ce que cela signifie ?</summary><p>Trois repères éditoriaux, pas trois garanties de résultat. D4 : scénarios documentés. D5 : montages plus agressifs, avec des conditions plus exigeantes. D6 : cas-limites dont l’analyse dépend fortement des faits. Le livre distingue les architectures défendables des contre-exemples qui franchissent une ligne rouge.</p></details></div></section>

    <section className="store-final"><div className="store-wrap"><p className="store-overline">LES RÈGLES SONT LES MÊMES. PAS LES QUESTIONS.</p><h2>Regardez votre argent<br/><em>autrement.</em></h2><BookAction href={guide ? (offer.ready ? offer.purchaseUrl : '#ouverture') : '/guide'} placement="final" purchase={guide && offer.ready}>{heroLabel}</BookAction><p className="store-small">Guide numérique · {offer.priceLabel} · Paiement unique</p></div></section><div id="services" className="store-services-bridge store-wrap"><p>Un sujet mérite d’être approfondi ? <a href="/services">Découvrir les décryptages sur demande ↗</a></p></div></main><StoreFooter/><div className="store-mobile-bar"><span>Le livre du Hibou<strong>{offer.priceLabel} · paiement unique</strong></span><BookAction href={heroTarget} placement="mobile" purchase={guide && offer.ready}>{guide ? (offer.ready ? 'Accéder au livre' : 'Me prévenir') : 'Voir le livre'}</BookAction></div><BookSignals/></div>;
}
