'use client';
import { useId, useState } from 'react';
import { track } from '@vercel/analytics';
import { capitalIllustration } from '../lib/book-marketing.mjs';

const money = value => new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 2 }).format(value) + ' €';
function record(mode, amount) { try { track('holding_lombard_explored', { mode, amount, version: '2026-10-03-marc' }); } catch {} }
export default function HoldingLombard() {
  const [mode, setMode] = useState('personal');
  const [amount, setAmount] = useState(100000);
  const id = useId();
  const values = capitalIllustration(amount);
  const holding = mode === 'holding';
  return <div className="store-comparison store-holding-lombard"><div className="store-comparison-header"><p className="store-overline">DIVIDENDES À DISTRIBUER, APRÈS L’IS DE LA SOCIÉTÉ</p><div className="store-amount-switch" role="group" aria-label="Montant de l’exemple">{[100000, 500000].map(value => <button type="button" key={value} aria-pressed={value === amount} onClick={() => { setAmount(value); record(mode, value); }}>{money(value)}</button>)}</div></div><div className="store-toggle" role="group" aria-label="Comparer les deux circuits"><button type="button" aria-pressed={!holding} aria-controls={`${id}-result`} onClick={() => { setMode('personal'); record('personal', amount); }}>Je touche les dividendes</button><button type="button" aria-pressed={holding} aria-controls={`${id}-result`} onClick={() => { setMode('holding'); record('holding', amount); }}>Holding + financement</button></div><div id={`${id}-result`} className={`store-comparison-result ${holding ? 'is-holding' : ''}`} aria-live="polite"><div className="store-flow"><span>Société opérationnelle</span><span aria-hidden="true">↓</span><strong>{holding ? 'Holding au régime mère-fille' : 'Vous, personnellement'}</strong></div><div><p className="store-result-number">{money(holding ? values.holding : values.personal)}</p><p className="store-result-label">{holding ? 'à réinvestir dans la holding, avant toute sortie personnelle' : 'sur votre compte personnel, après PFU'}</p></div></div><p className="store-comparison-takeaway">{holding ? `${money(values.retainedDifference)} de plus pour réinvestir dans la holding. Et l’idée ne s’arrête pas là.` : `${money(values.personalTax)} de PFU dans cet exemple. Toucher les dividendes n’est pas la seule logique à étudier.`}</p>
    <div className="store-lombard-path"><p className="store-overline">LA SUITE : NANTIR POUR EMPRUNTER</p><h3>Des liquidités personnelles.<br/>Sans distribuer le capital.</h3><div className="store-lombard-steps"><p><span>1</span>La holding conserve les fonds.</p><p><span>2</span>Vous proposez en garantie les titres de holding que vous possédez personnellement.</p><p><span>3</span>Si la banque les accepte, elle vous prête à titre personnel.</p></div><p className="store-lombard-punchline">L’argent reçu vient de la banque. Le capital reste dans la holding.</p><p className="store-small">Un prêt à rembourser, avec intérêts. Pour des titres de holding non cotés, l’acceptation relève d’une étude sur mesure, pas d’un crédit lombard standard automatique.</p></div>
    <details className="store-detail"><summary>Le calcul, le nantissement et les sources</summary><div><p><strong>Le calcul.</strong> Point de départ : {money(amount)} de dividendes après l’IS déjà payé par la société opérationnelle. Distribution personnelle au PFU de 31,4 % : {money(values.personalTax)} d’impôt, soit {money(values.personal)} nets. Hypothèse holding éligible au régime mère-fille : quote-part de 5 % à l’IS de 25 %, soit {money(values.holdingTax)} et {money(values.holding)} conservés dans la holding. Hors frais et cas particuliers. Une redistribution personnelle immédiate, au même PFU, laisserait {money(values.afterPersonalDistribution)} : l’écart de trésorerie n’est donc pas une exonération personnelle définitive.</p><p><strong>Le financement personnel.</strong> Le scénario à étudier consiste à nantir les titres de holding détenus personnellement par l’associé, et non à lui faire prêter les fonds par la holding. Pour des titres non cotés, la banque doit accepter la garantie, sa valorisation, la décote, le montant et la capacité de remboursement. Aucune quotité ni offre de financement n’est supposée acquise dans cet exemple. Le prêt crée une dette personnelle et des intérêts ; il ne fait pas sortir le capital de la holding et n’efface pas l’impôt d’une distribution future. Les contrats peuvent exiger un renforcement des garanties ou un remboursement si leur valeur baisse.</p><p><strong>Sources vérifiées le 3 octobre 2026.</strong> <a href="https://entreprendre.service-public.gouv.fr/actualites/A18796" target="_blank" rel="noopener noreferrer">Service Public : PFU à 31,4 %</a> · <a href="https://www.banquetransatlantique.com/fr/actualites/vendre-au-sein-de-votre-famille.html" target="_blank" rel="noopener noreferrer">Banque Transatlantique : régime mère-fille</a> · <a href="https://www.lesclesdelabanque.com/particulier/credit-lombard-emprunter-sans-vendre-placements/" target="_blank" rel="noopener noreferrer">Fédération bancaire française : crédit lombard</a> · <a href="https://www.boursobank.com/aide-en-ligne/banque-privee/credit-lombard/question/quels-sont-les-comptes-eligibles-au-credit-lombard-7707351" target="_blank" rel="noopener noreferrer">BoursoBank : exclusion des titres non cotés de son offre standard</a>. Ces sources décrivent les briques séparément ; elles ne prouvent pas l’accord d’une banque pour ce montage sur titres de holding.</p></div></details>
  </div>;
}
